apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ include "arch.namespace" . }}
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.user }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password }}
          ports:
            - containerPort: {{ .Values.rabbitmq.amqpPort }}
            - containerPort: {{ .Values.rabbitmq.managementPort }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.rabbitmq.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ include "arch.namespace" . }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.amqpPort }}
      targetPort: {{ .Values.rabbitmq.amqpPort }}
    - name: management
      port: {{ .Values.rabbitmq.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}